### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by proJM-Coding** [proJM1/proJM-pack#1]
This is a note to remind me that performance in this pack is not the best. This should be tested on and experimented on. This is a 16x pack and should work well normally.

**Comment by proJM1** [comment]
Zip file problem fixed. Going to test performance soon.

**Comment by proJM1** [comment]
Performance to be tested in 1-2 hours

**Comment by proJM1** [comment]
Fps capped at 60 fps. Chunks raised so that fps is impacted more to help get better results.
Without pack: 54-58 fps With: 51-57 fps
